### PR TITLE
title changed to siddharth628

### PR DESCRIPTION
**Pull request by siddharth628**

### CODE REVIEW

**Comment by jwflory** [comment]
Hi @siddharth628, it looks like you successfully completed #61 and created a feature branch. 👍🏻 There are quite a few changes in this Pull Request though. It looks like line spacing and alignment changes. Since a Pull Request was not required, I am going to close this PR and you can work on a new task.

**Comment by siddharth628** [comment]
Hi @jwflory, I am still figuring out how everything works so I guess the changes are because of that, I am getting an error "Error: add site dependencies: load resources: loading templates: "/Users/siddharth/outreachy/inventory/themes/inventory/layouts/partials/head.html:5:1": parse failed: template: partials/head.html:5: unterminated quoted string" whenever I attempt to run the command hugo serve, I am trying to resolve it. I will notify you if I fail to resolve it by myself.

**Comment by siddharth628** [comment]
I see now PR was not necessary.

**Comment by jwflory** [comment]
> I am getting an error "`Error: add site dependencies: load resources: loading templates: "/Users/siddharth/outreachy/inventory/themes/inventory/layouts/partials/head.html:5:1": parse failed: template: partials/head.html:5: unterminated quoted string`" whenever I attempt to run the command `hugo serve`

It looks like you may have other code changes in your fork. This Pull Request included many different changes other than the title change too. You might check if your IDE is automatically formatting files, and turn that feature off for this project if so.

> I see now PR was not necessary.

No worries! 👍🏻

**Pull request closed without merging**
