### PR TITLE
Add condition to only show "RA Section" when there's content available

### PR DESCRIPTION
**Pull request by mmldco**
This commit partially fixes issue #30. The reason I've submitted it as a partial fix is because, the referenced issue doesn't seem to just affects pages inside this repository but also pages inside the cohorts directory located inside this themes' parent directory .i.e. `unicef/inventory`. I will submit a separate pull request on the parent directory to fix the issue there.

### CODE REVIEW

**Comment by jwflory** [comment]
Hey @mmldco, thanks for submitting this. I'll review it shortly.

Also, as a note, it is best practice to first comment on an issue that you are interested in working on so it can be assigned to you. I think @Yavnikaa had started to work on this per her comment in #30, and skipping the step of commenting in an issue often causes duplicated efforts. We'd like to avoid that, especially with more folks coming to find this project in the coming weeks.

**Comment by Yavnikaa** [comment]
Ahh, so shall I take up some other issue? So that neither of our effort goes waste. 
@jwflory can you allot me some other good first issue to begin with?

**Comment by mmldco** [comment]
@jwflory I completely understand. @Yavnikaa my sincerest apologies.

**Review by jwflory — CHANGES_REQUESTED** [review]
I see where you are going with this, and it does fix the issue on some index pages for the categories. But it does not fix the problem on content pages. In effect, the _Related Articles_ header is only hidden if a page has no content like some index pages. On pages where there is content, the _Related Articles_ header still appears.

A better approach for this would be to use a check if the list of articles from the category is empty, and if it is empty, do not show this HTML `<section>`.  My first suspicion is this is being checked in the `$taxonomy` variable, which is iteratin through the `.Site.Taxonomies.categories` list. I could be wrong though.

My idea for a fix might be to play around with the order of how this loop is constructed and to move some HTML elements later on in the loop after checking whether the taxonomy list is empty. [Hugo functions](https://gohugo.io/functions/) should provide useful context to the existing script block here and how it could be improved to fix this bug.

Does this feedback sense? Are you up for working on this further?

Also, for the _Cohorts_ section, don't pay too much mind to that… the code for the _Cohorts_ category is in the `unicef/inventory` repo, but eventually, we want to consolidate it into the `unicef/inventory-hugo-theme` repo (see #35). But that is more complex and will probably take time. I wouldn't advise starting on that yet. So don't worry if your changes don't appear correctly in the _Cohorts_ category just yet.

**Comment by mmldco** [comment]
The latest commit should fix the both #30 and the new bug introduced by commit e4a8438b34162f83b9efaa8d6b535b1263f50cd8.

**Comment by mmldco** [comment]
After some further testing I'm realising that the above fix seems to only work for top level index and content pages.  The fix is somewhat buggy when it comes to nested pages. I'm currently trying to figure out whether the issue is the composition of the fix or how pages on the different levels have been tagged. I'll report back with findings.

**Comment by jwflory** [comment]
@mmldco Not sure what you mean by nested pages. Could you please clarify? I tried pulling your changes locally and it seems like they are working right in the example site and the Open Source Inventory, but I didn't look too closely.

**Comment by mmldco** [comment]
@jwflory I was to categories such as 'Meta' which has sub-categories (nested pages). That being said I've undone the code refactoring I introduced in commit 3f534ddb18dbc3a02e1b437b3e74ae82ac42dc7f. I was trying to enhance the logic but it seems like it was breaking something. You can proceed to close this issue as the latest commit fixes it. I'll keep making changes locally to see whether I can improve on it. If I'm successful, I'll create a separate pull request with details of the specific problem it addresses.

**Pull request merged**
