### PR TITLE
Show big quotes for blockquote citations

### PR DESCRIPTION
**Pull request by Idadelveloper**
@jwflory I forgot to include this change when I got rid of the changes I made regarding the font. This link to font awesome helps with the display of the big quotes.

### CODE REVIEW

**Comment by jwflory** [comment]
Hey @Idadelveloper, was this still needed after all? I just noticed this Pull Request.

**Comment by Idadelveloper** [comment]
> Hey @Idadelveloper, was this still needed after all? I just noticed this Pull Request.

Hey @jwflory . It wasn't. I kinda got mixed up 😅

**Comment by jwflory** [comment]
All good! Thanks for following up. 👍🏻

**Comment by Idadelveloper** [comment]
Hey @jwflory. Reopening this PR because it's supposed to make the big quotes show for a citation (https://unicef.github.io/inventory/foss/gpl-comparison/). I just checked and doesn't seem to be there. I think I got mixed up and closed it for no reason.

**Comment by jwflory** [comment]
@Idadelveloper Good catch. This is a good first Pull Request to close out for this week. 👍🏻

**Comment by jwflory** [comment]
Duplicated by #8. Closing! 🎬

**Pull request closed without merging**
