### PR TITLE
added more social media platforms

### LINKED ISSUE #130: As a prospective open source contributor, I want to find more platforms and social media channels (e.g. Facebook, Instagram) on Team Profiles so that I can connect with UNICEF-supported companies who build open source projects.
### Summary

This helps start-up companies supported by the UNICEF Venture Fund identify community engagement channels. Currently, the Team Profiles feature supports a handful of social media platforms, but we should expand that to Facebook, Instagram, and possibly others.

See [OTTAA Project team profile](https://github.com/unicef/inventory/pull/91/files#r762002045).

### Priority

secondary

### Category

front-end

### Type

functional

### PR DESCRIPTION
**Pull request by Neha9849**
Fixes #130 
I have added Facebook and Instagram. Is there anything more we should add?

### CODE REVIEW

**Review by jwflory — CHANGES_REQUESTED** [review]
Hey @Neha9849, thanks for tackling this one. Two comments before we merge this one in:

1. There is a bug in the Facebook section, see below.
2. Let's group like parts together. Social media presence like Facebook and Instagram should be grouped together with Twitter and LinkedIn instead of appending to the bottom of the profile. The website and community info should remain on the bottom.

**Comment by Neha9849** [comment]
@jwflory I should just change the order right?
or should I group them into different sections?

**Comment by jwflory** [comment]
@Neha9849 The minimum required task is to put them in the right order, but you could propose a layout tweak here as well, if you have a creative vision.

**Review by jwflory — APPROVED** [review]
Looks good. Thanks @Neha9849! We can test this out by adding some of the social media information for projects like the OTTAA Project. Merging. 🎬

**Pull request merged**
