### PR TITLE
Fixes#107

### PR DESCRIPTION
**Pull request by Neha9849**
Added inventory layouts to theme repo

### CODE REVIEW

**Comment by jwflory** [comment]
This should be straightforward to test. I will review this earlier in the day on Thursday. I am getting ready to sign off for the night.

However, in the meantime, it seems like there is an issue with git commit history that needs to be amended. @Neha9849, it looks like your `main` branch in your local repo may be behind from the UNICEF remote. When you check out a new branch, it uses the same state as the current branch. Could you see if your local `main` branch is missing new commits or whether it needs a hard reset? Until the root issue is resolved, it will keep showing up in PRs with the several commit messages for things like the PDF embed page.

This is where git starts to get fun 😅

**Comment by Neha9849** [comment]
My main branch is ahead  of the UNICEF remote branch. I don't know why this happened.
Yesterday , I tried rebasing and messed up something and ended up closing the other PR.
Now, I tried git `reset` and it worked. Now my main branch is even with this repo main.

**Comment by Neha9849** [comment]
For my edit-this-btn branch, if I do hard reset than this PR will get close. Should I do hard reset ? or this there any other solution?

**Review by jwflory — APPROVED** [review]
I tested this locally and it checks out with unicef/inventory#133. The changes here are ready to merge. 🎬 Thanks @Neha9849!

**Comment by jwflory** [comment]
> **@Neha9849 wrote…**
> For my edit-this-btn branch, if I do hard reset than this PR will get close. Should I do hard reset ? or this there any other solution?

The pull request will close automatically if the branch is ever deleted from the repository. This is likely what happened. You should be able to do a hard reset and then force-push changes without deleting the git branch. Then the changes should take effect in the same pull request.

I'm also going to take a look and see if I can get it mergeable before signing off.

**Comment by jwflory** [comment]
I rebased, squashed down to a single commit, and force-pushed changes to this branch. I am going to merge now – it is ready to go! 🌊

**Pull request merged**
