### PR TITLE
Issue 34: download template

### PR DESCRIPTION
**Pull request by ElHombreMorado8**
Download template added and an example page
http://localhost:1313/inventory-hugo-theme/downloads/download1/

Signed-off-by: <irismurillorobla@gmail.com>

### CODE REVIEW

**Comment by ElHombreMorado8** [comment]
@jwflory I created the first proposal. I'll wait for your feedback

**Comment by jwflory** [comment]
Hi @ElHombreMorado8, I'm sorry I did not respond to this sooner. Are you still interested in finishing this Pull Request?

For reference, here is a screenshot of the change as I saw it. I will also attempt a rebase of this Pull Request on the latest changes in `main`.

Screenshot of the download example page for an image and a PDF

**Comment by jwflory** [comment]
Hi @ElHombreMorado8, following up here. Our current sprint ends this Friday, 24 June. I'd like to close out this Pull Request by then. If you are interested in working on this, I can extend the deadline. Otherwise, I will close out this Pull Request. I would appreciate it if you let me know what your intent is either way. No pressure if you need to pass on this! Thanks again for your efforts on this Pull Request.

**Comment by ElHombreMorado8** [comment]
I have made this for the collaboration with outreachy. I'm working in other
projects and I don't have time to continue with it.
Thanks.

**Comment by jwflory** [comment]
@ElHombreMorado8 Understood. Thanks for following up. All the best on your future endeavors. 🚀

**Pull request closed without merging**
