### PR TITLE
changed primary button styling on hover

### LINKED ISSUE #112: CSS fix in cohorts page
# Summary

The buttons are not visible on hover.

# How to reproduce?

1. Changing the styling of the buttons on hover

**Screenshots**:

image

### PR DESCRIPTION
**Pull request by Neha9849**
Fixes #112 
I took the background color of primary button on hover state from the UNICEF main website to make inventory consistent with the main website.

### CODE REVIEW

**Review by jwflory — CHANGES_REQUESTED** [review]
The change makes sense, but hard-coding a color makes customization more difficult. For example, one downstream site is the [Sustain Design & UX knowledgebase](https://sustainers.github.io/design/), which has different color schemes than a UNICEF-branded site. For this reason, we should use one of the colors already provided in the config file to balance it out.

Could you try experimenting with the color variables already defined, and if needed, propose change to the color in the downstream theme to accomodate this? Let me know if have any follow-up questions.

**Comment by jwflory** [comment]
@Neha9849 Okay, we can leave this Pull Request as in progress. Think you can get this one ready for final review by the end of the week?

As a reminder, don't forget to rebase your changes on the latest changes in `main`. I see the sidebar partial was re-added but I think this was unintentional from a `git merge` to this feature branch.

**Comment by Neha9849** [comment]
replicated the changes in #131 and closing this.
I'm always messing things up while rebasing, i don't understand why this keep's on happening to me.

**Comment by jwflory** [comment]
@Neha9849 As we discussed earlier today, we'll walk through it together on the next rebase. 💪🏻 It's an advanced git skill, so some hiccups on the way are inevitable! You got this. 😀 

Moving over to #131.

**Pull request closed without merging**
