### PR TITLE
:new: :memo: exampleSite: Add forking and reuse docs (closes #118)

### LINKED ISSUE #118: As a developer, I want clear documentation on forking so that I can reuse the Inventory theme for a new project.
### Summary

Related to #89.

### Priority

primary

### Category

documentation

### Type

business

### PR DESCRIPTION
**Pull request by jwflory**
This commit creates new documentation about how to fork and reuse the
UNICEF Inventory theme in new projects, whether for a new Hugo website
or as a UNICEF Toolkit. This replaces the content formerly found in the
`/content/install/` directory.

Additionally, weights were assigned to all categories so that the
categories appear on the home page in a specific order. The weights
start from `20` because eventually, the `/content/about/` section will
use a weight of `10`, putting it before other categories.

Also, some Spanish content was added to demonstrate the multilingual
features of the site, but more work should be done to translate the
content to provide a meaningful example of this feature in practice.

Closes #118.

Local preview of the page explaining how to create a new Hugo website with the UNICEF Inventory theme.

Local preview of the page explaining how to create a new UNICEF Toolkit with the UNICEF Inventory theme.

### CODE REVIEW

**Comment by jwflory** [comment]
@siddharthvipul, would you be up for a pass on reviewing this PR? Since you are newly incoming, your feedback and perspective here are very useful! 🙏🏻

**Comment by jwflory** [comment]
@nathanbaleeta or @nathanfletcher, your feedback on this Pull Request is also useful to understand whether the reuse instructions for the wider Office of Innovation are clear! 🙏🏻

**Comment by jwflory** [comment]
@Idadelveloper and @Neha9849, your feedback on this docs Pull Request is also helpful as previous interns on the project. If you have time to take a look, your feedback and questions are appreciated! 🙏🏻

**Review by Idadelveloper — APPROVED** [review]
@jwflory looks good to me

**Comment by siddharthvipul** [comment]
> @siddharthvipul, would you be up for a pass on reviewing this PR? Since you are newly incoming, your feedback and perspective here are very useful! 🙏🏻

PR looks good to me, @jwflory :)
+1

**Comment by jwflory** [comment]
Thanks @Idadelveloper and @siddharthvipul! I appreciate your reviews. Merging. 🌊

**Pull request merged**
