### PR TITLE
:new: :memo: .github: Add contributing guidelines

### PR DESCRIPTION
**Pull request by jwflory**
This commit adds new contributing guidelines for the UNICEF Inventory theme. It includes four main topics:

1. Contribution process (a.k.a. governance)
2. Conventions & courtesies
3. Structure & components
4. How to create a developer environment

### CODE REVIEW

**Comment by jwflory** [comment]
@Idadelveloper Could you please proofread and leave a review on the contributing guidelines for the theme? Your feedback is especially useful here 🔍

**Review by Idadelveloper — COMMENTED** [review]
Hi @jwflory, you can add creating a branch related to the issue before making changes. Also, they should try tagging the issue they are fixing in the PR message body.

**Comment by jwflory** [comment]
Good feedback @Idadelveloper 👍🏻 I pushed commit 2d4ec1ec155faf6e41c703686a4742187a533934 to address your feedback. Could you please re-review?

**Review by Idadelveloper — APPROVED** [review]
Looks good to me :)

**Comment by jwflory** [comment]
Thanks @Idadelveloper. Merging. 🌊

**Pull request merged**
